apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-nginx-php
  labels:
    name: dp-nginx-php
spec:
  replicas: 2
  selector:
    matchLabels:
      web: nginx-php
      tier: front-end
  template:
    metadata:
      name: nginx-php-pod
      labels:
        web: nginx-php
        tier: front-end
    spec:

      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
      - name: shared-files
        emptyDir: {}

      containers:

      - name: php-ctr
        image: deepcloudmosphere/dp-nginx-php:phpfpm-code
        ports:
        - containerPort: 9000


        volumeMounts:
        - mountPath: /var/www/html/
          name: shared-files

        # Important! After this container has started, the PHP files
        # in our Docker image aren't in the shared volume. We need to 
        # get them into the shared volume. If we tried to write directly
        # to this volume from our Docker image the files wouldn't appear
        # in the nginx container.
        #
        # So, after the container has started, copy the PHP files from this
        # container's local filesystem (/app -- added via the Docker image) 
        # to the shared volume, which is mounted at /var/www/html.

        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "cp -r /app/. /var/www/html"]

        # env variable for mysqli connector in php image 

        env:
        # database user
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: php-db-configmap
              key: USER
        #database host
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: php-db-configmap
              key: HOST
        # database password
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: php-db-secret
              key: DB_PASSWORD
        # database name
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: php-db-secret
              key: DB_DATABASE

      - name: nginx-ctr
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/html/
          name: shared-files
        - mountPath: /etc/nginx/conf.d/
          name: nginx-config-volume







      ##################################you can also use init container for code #######################

      # initContainers:
      # - name: init-myservice
      #   image: deepcloudmosphere/dp-nginx-php:init-helper
      #   command: ['sh', '-c', 'git clone https://github.com/Dountless/web-app-ecommerce.git/ /opt/']
      #   volumeMounts:
      #   - mountPath: /opt/
      #     name: my-data
      ######################################################################################################









