apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-dp
  labels:
    tier: back-end
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: back-end
      web: db
  template:
    metadata:
      name: mariadb-pod
      labels:
        tier: back-end
        web: db
    spec:

      volumes:
      - name: mysql-data
      - name: mysql-product-data
        configMap:
          name: db-load-script

      containers:
      - name: mariadb-ctr
        image: mariadb
        ports:
        - containerPort: 3306
        #environment variable from cofigmap
        envFrom:
        - configMapRef:
            name: mysql-config
        # volume mount into mysql ctr
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
        - mountPath: /docker-entrypoint-initdb.d #this dir executed when ctr will start 
          name: mysql-product-data



