apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-dp
  labels:
    tier: back-end
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: back-end
      web: db
  template:
    metadata:
      name: mariadb-pod
      labels:
        tier: back-end
        web: db
    spec:

      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: db-pv-claim

      - name: mysql-product-data
        configMap:
          name: db-load-script

      containers:
      - name: mariadb-ctr
        image: mariadb:10.8.6
        ports:
        - containerPort: 3306
        #environment variable from cofigmap
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: php-db-secret
              key: MYSQL_ROOT_PASSWORD

        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: php-db-configmap
              key: USER

        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: php-db-secret
              key: DB_PASSWORD

        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: php-db-secret
              key: DB_DATABASE

        # volume mount into mysql ctr
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
        - mountPath: /docker-entrypoint-initdb.d #this dir executed when ctr will start 
          name: mysql-product-data



