apiVersion: v1
kind: Service
metadata:
   name: svc-nginx-php
spec:
   type: NodePort
   ports:
     - port: 80
       targetPort: 80 
       nodePort: 30004
   selector:
     web: nginx-php
     tier: front-end

     
