apiVersion: v1
kind: Service
metadata:
    name: db
    labels:
       tier: backend
 
spec:
   type: ClusterIP
   ports: 
    - targetPort: 3306
      port: 3306
   
   selector: 
     app: mysqldb
     tier: backend
  
   
