apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv-volume
spec:
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  # awsElasticBlockStore:
  #   volumeID: vol-0d20eea097c3942f3
  #   fsType: ext4
  hostPath:
    path: /home/vagrant/db-pv-volume-data
